name: rich_text_controller
description: An extended text editing controller that supports different inline styles for custom regex patterns
version: 2.0.0
homepage: https://github.com/micazi/rich_text_controller

environment:
  sdk: ">=3.1.1 <4.0.0"
  flutter: ">3.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
